# Modulo Numpy

In [1]:
# Carguemos el modulo numpy
import numpy as np

In [ ]:
# Documentacion del modulo
help(np)

In [ ]:
# # Numpy provee una serie de submodulos/subpaquetes

# random
#         Core Random Tools
#     linalg
#         Core Linear Algebra Tools
#     fft
#         Core FFT routines
#     polynomial
#         Polynomial tools

In [ ]:
# Elementos que componen al modulo numpu
dir(np)

In [4]:
# Elementos que componen al modulo random
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_bit_generator',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_bit_generator',
 'set_state',
 'shuf

In [ ]:
# Documentacion del modulo random
help(np.random)

In [ ]:
# Documentacion de la funcion triangular del submodulo random del modulo numpy
help(np.random.triangular)

In [7]:
# unidimensional
v1 = np.random.triangular(12,14,16,10)
v1

array([14.34094471, 15.25348381, 14.12210635, 13.73289131, 13.58084938,
       13.83967293, 12.54558411, 14.19621867, 14.64933782, 13.57228297])

In [8]:
# Bidimensional
v2 = np.random.triangular(12,14,16,(3,4))
v2

array([[14.28207774, 13.61854679, 14.09506351, 13.74867915],
       [14.79542278, 14.94734   , 13.94610872, 15.15054124],
       [14.61199491, 13.66355187, 14.08873077, 13.19649005]])

In [9]:
# Tridimensional
v3 = np.random.triangular(12,14,16,(2,3,4 ))
v3

array([[[13.76955578, 14.8947837 , 13.50756372, 13.30381363],
        [13.61308734, 14.02461494, 13.87577175, 14.00119283],
        [12.70127701, 13.48107906, 15.15908921, 14.07742653]],

       [[13.57517189, 14.1889546 , 12.88199783, 13.54402298],
        [15.75424433, 13.42705992, 13.42913727, 15.18448489],
        [15.99145404, 15.10198439, 13.87628206, 13.81969086]]])

In [10]:
# Antepenultima componente del objeto unidimensional v1
v1[-3]

14.196218671708412

In [ ]:
# Accedamos a elementos del objeto bidimensional v2


In [11]:
# Tercera columna de v2
v2[:,2]

array([14.09506351, 13.94610872, 14.08873077])

In [12]:
# Tercera fila de v2
v2[2,:]

array([14.61199491, 13.66355187, 14.08873077, 13.19649005])

In [14]:
# Mostremos la primera y ultima columna de v2
v2[:,(0,-1)]

array([[14.28207774, 13.74867915],
       [14.79542278, 15.15054124],
       [14.61199491, 13.19649005]])

In [16]:
# Accedamos a elementos de un objeto tridimensional
v3[0,(1,2),1]

array([14.02461494, 13.48107906])

In [17]:
# tipo de dato
type(v1)

numpy.ndarray

In [18]:
# tipo de dato
type(v2)

numpy.ndarray

In [20]:
# tipo de dato
type(v3)

numpy.ndarray

In [21]:
# Acceso a los metodos de un dato de tipo ndarray de numpy
dir(v3)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o